import type { Metadata } from "next";
import Navigation from "./components/ui/nav";
import Footer from "./components/ui/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>

        <Navigation/>
        
        <div className="mx-auto flex w-full max-w-7xl flex-1 flex-col px-4 pb-6 pt-2 sm:px-6 lg:px-8">
          
          {children}

        </div>

        <Footer/>

      </body>
    </html>
  );
}
